name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a compatible Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
        pip install -e . # Install project in editable mode to resolve local imports

    - name: Build Sphinx documentation
      run: |
        # Temporarily comment out problematic imports for Sphinx build
        sed -i 's/^from \.DummyPoints import DummyPoints/# from .DummyPoints import DummyPoints/' src/ai4bmr_datasets/datasets/__init__.py
        sed -i 's/^from \.DummyImages import DummyImages/# from .DummyImages import DummyImages/' src/ai4bmr_datasets/datasets/__init__.py
        sed -i 's/^from \.DummyTabular import DummyTabular/# from .DummyTabular import DummyTabular/' src/ai4bmr_datasets/datasets/__init__.py
        
        /Users/adrianomartinelli/.venv/ai4bmr-learn/bin/sphinx-build -b html docs/source docs/build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        publish_branch: gh-pages # The branch to publish the documentation to
